In [2]:
import numpy as np
mylist1 = [1,2,3,4]
myarray1 = np.array(mylist1)
myarray1

array([1, 2, 3, 4])

In [3]:
mylist2 = [11,22,33,44]
mylists = [mylist1,mylist2]
myarray2 = np.array(mylists)
myarray2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [5]:
myarray2.shape

(2L, 4L)

In [6]:
myarray2.dtype

dtype('int32')

In [7]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
myzerosarray = np.zeros(5)
myzerosarray.dtype

dtype('float64')

In [9]:
np.ones(shape=(5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
#Same as np.zeros
np.empty([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.arange(1,100,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])