In [1]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[8]

8

In [3]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [4]:
arr[0:4] = 40
arr

array([40, 40, 40, 40,  4,  5,  6,  7,  8,  9, 10])

In [6]:
slice_of_array = arr[:]
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [7]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [10]:
arr1 = arr.copy()
arr1

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [11]:
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
print arr2d[1]
print arr2d[0]

[20 25 30]
[ 5 10 15]


In [14]:
arr2d[2][1]

40

In [15]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [17]:
arr3 = np.zeros(shape=(10,10))
arr3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [23]:
arr3.shape[1]

10L

In [33]:
for i in range(arr3.shape[1]):
    arr3[i] = i
arr3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [34]:
#Fancy indexing
arr3[[3,5,6,2]]

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]])