In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [4]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1=Series([0,1,2],index=['T','U','V'])
ser2=Series([3,4],index=['X','Y'])
print ser1
print ser2

T    0
U    1
V    2
dtype: int64
X    3
Y    4
dtype: int64


In [11]:
pd.concat([ser1,ser2],axis=0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [15]:
dframe1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2=DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])
print dframe1
print dframe2

          X         Y         Z
0  0.687208  0.290932  0.413110
1  1.507365  0.610289  1.145325
2  1.760354 -0.502329  0.355531
3 -0.614728 -0.477328  1.196341
          Y         Q         X
0 -0.528750 -1.734056 -0.909347
1  0.071296 -0.604322  1.158413
2  0.487900  1.699419 -1.047284


In [16]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.687208  0.290932  0.413110
1       NaN  1.507365  0.610289  1.145325
2       NaN  1.760354 -0.502329  0.355531
3       NaN -0.614728 -0.477328  1.196341
0 -1.734056 -0.909347 -0.528750       NaN
1 -0.604322  1.158413  0.071296       NaN
2  1.699419 -1.047284  0.487900       NaN

In [20]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.687208  0.290932  0.413110
1       NaN  1.507365  0.610289  1.145325
2       NaN  1.760354 -0.502329  0.355531
3       NaN -0.614728 -0.477328  1.196341
4 -1.734056 -0.909347 -0.528750       NaN
5 -0.604322  1.158413  0.071296       NaN
6  1.699419 -1.047284  0.487900       NaN