In [2]:
import numpy as np

In [3]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
np.exp(arr)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03])

In [6]:
arr2 = np.random.randn(10)
arr2

array([ 1.73650769, -0.5444848 , -1.06341678,  0.34684342, -1.60848289,
        0.16805566,  0.52470373, -0.26394882,  0.19323141,  0.17790741])

In [8]:
arr3 = np.random.randn(10)
arr3

array([-0.6269106 ,  0.52056913,  2.21236095,  1.82002884,  0.84599984,
        1.49318212,  1.41721205,  0.06934545, -0.40555578, -0.05822655])

In [9]:
#Binary function
np.add(arr2,arr3)

array([ 1.1095971 , -0.02391567,  1.14894417,  2.16687226, -0.76248305,
        1.66123778,  1.94191579, -0.19460337, -0.21232437,  0.11968086])

In [10]:
np.maximum(arr2,arr3)

array([ 1.73650769,  0.52056913,  2.21236095,  1.82002884,  0.84599984,
        1.49318212,  1.41721205,  0.06934545,  0.19323141,  0.17790741])

In [ ]:
website = 