In [1]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray',arr)

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.load('myarray.npy')
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr1 = np.load('myarray.npy')

In [11]:
np.savez('ziparray.npz',x = arr1,y=arr)

In [12]:
archive_array = np.load('ziparray.npz')

In [18]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [19]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.savetxt('mytextfile.txt',arr,delimiter=',')

In [23]:
arr = np.loadtxt('mytextfile.txt',delimiter=',')
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])